// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_WEB']!,
        appId: '1:933102750137:web:25e0b4502889b5706e0e68',
        messagingSenderId: '933102750137',
        projectId: 'first-haid',
        authDomain: 'first-haid.firebaseapp.com',
        storageBucket: 'first-haid.firebasestorage.app',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID']!,
        appId: '1:933102750137:android:de29324dc24fa60b6e0e68',
        messagingSenderId: '933102750137',
        projectId: 'first-haid',
        storageBucket: 'first-haid.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_IOS']!,
        appId: '1:933102750137:ios:af751b80ee4c3edf6e0e68',
        messagingSenderId: '933102750137',
        projectId: 'first-haid',
        storageBucket: 'first-haid.firebasestorage.app',
        iosBundleId: 'com.dbn.firstHaid',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_MACOS']!,
        appId: '1:933102750137:ios:af751b80ee4c3edf6e0e68',
        messagingSenderId: '933102750137',
        projectId: 'first-haid',
        storageBucket: 'first-haid.firebasestorage.app',
        iosBundleId: 'com.dbn.firstHaid',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_WINDOWS']!,
        appId: '1:933102750137:web:5a2106114b2a46916e0e68',
        messagingSenderId: '933102750137',
        projectId: 'first-haid',
        authDomain: 'first-haid.firebaseapp.com',
        storageBucket: 'first-haid.firebasestorage.app',
      );
}
